version: '3.7'

services:
    coupons_db:
        image: postgres:12.1-alpine
        ports:
            - 5432:5432
        environment:
           - POSTGRES_PASSWORD=password
           - POSTGRES_USER=postgres
           - POSTGRES_DB=coupons_develop
        volumes:
            - postgres_data_coupons/var/lib/postgresql/data
volumes:
  postgres_data_coupons:
